mopl:
  storage:
    type: ${STORAGE_TYPE:local}

    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.mopl/storage}
      # 로컬 이미지 접근을 위한 기본 주소 (API 서버 주소)
      base-url: ${STORAGE_LOCAL_BASE_URL:http://localhost:8080}

    s3:
      access-key: ${AWS_S3_ACCESS_KEY:}
      secret-key: ${AWS_S3_SECRET_KEY:}
      region: ${AWS_S3_REGION:ap-northeast-2}
      bucket: ${AWS_S3_BUCKET:}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}